CREATE TABLE student (student_id BIGSERIAL PRIMARY KEY, name TEXT);
CREATE TABLE contact (contact_id BIGSERIAL PRIMARY KEY, student_id BIGINT, contact_number TEXT);

ALTER TABLE student REPLICA IDENTITY FULL;
ALTER TABLE contact REPLICA IDENTITY FULL;
